# Universe should always be 'vanilla' unless you know explicitly what you're doing
universe = vanilla

# this sets the environment variables of the login environment to the compute node environment
# generally, you will want to leave this set to true
getenv = true

# this is the command or program you are running. 

executable = /home/criley38/filter-marta-data/condor.sh

# this is a space delimited list of arguments sent to the program listed above. the path to and name of your script go here for example, along with any other arguments
# if you need to run multiple copies of your job you can pass $(Process) as an argument which will increment by one, starting at zero, for every process spawned 
# for any files that you are using, you should pass the entire path. for example, for a file 'script.py' in your home directory use:

arguments = /home/criley38/filter-marta-data/instances/january.txt $(process)
 

# this is the name and location of the Condor logs for your job. This will show details of what Condor itself is doing in relation to your job, but not the output of your job (for that, see the next entries)

log = $ENV(HOME)/filter-marta-data/logs/$(Cluster).log

# this is the name and location of the actual output from your job. 
# output will contain whatever would've been sent to the screen (aka STDOUT) 
# error will contain any errors generated by your application (aka STDERR)
# the variable $(cluster) will generate one number per run of "condor_submit"
# the variable $(process) will generate a unique number for every job generated within this script, starting at zero

output = $ENV(HOME)/filter-marta-data/logs/$(Cluster).$(process).out
error = $ENV(HOME)/filter-marta-data/logs/$(cluster).$(Process).error

# these options will notify the email listed below if the job errors out or when it completes
# comment or delete these lines if you do not wish to get an email
# you will get an email for each instance of your job, so if you spawn 50 jobs you will get 50 emails.
# use notification = none if you do not want to get any email about the job

# If you need a specific amount of memory, uncomment the line below and change the number to the minimum amount of RAM you need for your job. This number is in megabytes.

request_memory = 16000
request_cpus = 1
# the queue command is REQUIRED
# if you need to run this more than once, enter the number of copies after the queue command
# for every copy spawned, the variable $(process) will increment by one, starting at zero. 
# if you only wish this to run once, leave the queue command with no number. 
# for example "queue 50" will spawn 50 copies of this job

queue 6200
